### ISSUE TITLE
CircleCI Integration

### ISSUE THREAD

**Issue by mmore500** [mmore500/presentation-template#2]
Following up here on suggestion from @vsoch in #1 suggesting a CircleCI integration. Love the idea! I did a little research into CircleCI, and came up with some ideas for what we might want to do:
1. confirm that we can build a Singularity container without an error from our `Singularity` build file,
2. confirm that we can compile our LaTeX without errors via the Singularity container (e.g., via `singularity run`),
3. :question: confirm that Singularity-compiled pdf matches a canonical version (e.g., in `example`),
4. confirm that we can build a Docker container without an error from our `Docker` build file,
5. confirm that we can compile our LaTeX without errors via the Docker container (e.g., via `Docker run`),
6. :question: confirm that Docker-compiled pdf matches a canonical version (e.g., in `example`),
7. :question: :question: deploy the Docker container via DockerHub when merged into master.
   * I know that SingularityHub builds containers for you, but I'm not as familiar with Dockerhub. I saw this kind of continuous-deployment mentioned in an intro on CircleCI.

Would love some feedback if I'm on the right track about the kinds of good things that are possible with CircleCI! :racing_car: :racing_car:

**Comment by vsoch** [comment]
All of this is doable and easy. I’d recommend skipping Singularity and pushing to Docker Hub and the user can pull the Docker uri into singularity. If you connect a basic repo to circle CI and export DOCKER_USER DOCKER_PASS and CONTAINER_NAME  to score to correspond with the docker repository that you want the build to be pushed you I’d be glad to write this configuration for you .

**Comment by mmore500** [comment]
Great!! I set up a docker repo at https://hub.docker.com/r/mmore500/presentation-template/ and put the tokens you mentioned in as environment variables on CircleCI.

![image](https://user-images.githubusercontent.com/10763333/46635517-c63ccc80-cb22-11e8-991f-30d43d6756e1.png)

I set container name as presentation-template (the DockerHub repo name).

**Comment by mmore500** [comment]
I started a pull request #3 with some boilerplate configuration files. If you like, feel free to work on this branch (I gave you push access) or just push to master.

**Comment by vsoch** [comment]
Perfect! Actually I have some already started so I'll just open a new PR. Thanks though! Let's get #1 merged first so I can start from that as master.

**Comment by mmore500** [comment]
Perfect!

**Comment by vsoch** [comment]
@mmore500 how would you like to handle versioning? if you want to use bumpversion (manual updates?) then could you show me how to use the command line tool to get the version for the present build? Otherwise, I'll use the first 10 characters of the commit (and not use bumpversion). Another manual (and easy way) is just to have  a VERSION file in the repo that we cat and read to populate the container, and it's tag.

**Comment by mmore500** [comment]
For Docker, let’s just use the first 10 characters of the commit. If we need a new version for every commit to push to dockerhub, that makes the most sense.

**Comment by mmore500** [comment]
Maybe we could add a LABEL line and put the source version separately, like

```
LABEL source version 1.0.0
```

and then do the first 10 of commit magic for `label VERSION=`part

**Comment by vsoch** [comment]
What is the difference?

**Comment by vsoch** [comment]
And a label can only have two things, so if you want the LABEL of key "source" to have value "version 1.0.0" you would do like:

```
LABEL source "version 1.0.0"
```
Is that what you mean?

**Comment by mmore500** [comment]
Oh! Didn’t know that. Yeah!

**Comment by vsoch** [comment]
hey so unfortunately you set the container name wrong - the full uri is `mmore500/presentation-template` and if you just do `presentation-template` it implies collection "library" which is owned by Docker Hub (permission denied). I'll fix this up, and we will have to wait for the build --> deploy again.
